"""Add test generation metadata fields

Revision ID: f4e4da42c823
Revises: db5b77c9235b
Create Date: 2026-01-28 09:28:40.997233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4e4da42c823'
down_revision: Union[str, None] = 'db5b77c9235b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_notes', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('class_notes', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('class_notes', 'created_at')
    op.add_column('gifts', sa.Column('points_cost', sa.Integer(), nullable=True))
    op.add_column('gifts', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('gifts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('gifts', 'probability')
    op.add_column('homework', sa.Column('corrected_text', sa.Text(), nullable=True))
    op.add_column('homework', sa.Column('is_reviewed', sa.Boolean(), nullable=False))
    op.add_column('homework', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('homework', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('homework', 'parent_reviewed')
    op.drop_column('homework', 'title')
    op.drop_column('homework', 'created_at')
    op.drop_column('homework', 'updated_at')
    op.add_column('questions', sa.Column('question_order', sa.Integer(), nullable=False))
    op.add_column('questions', sa.Column('points', sa.Integer(), nullable=False))
    op.alter_column('questions', 'options',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('questions', 'correct_answer',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.drop_column('questions', 'created_at')
    op.add_column('rewards', sa.Column('source_type', sa.String(length=50), nullable=False))
    op.add_column('rewards', sa.Column('source_id', sa.Integer(), nullable=True))
    op.add_column('rewards', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_column('rewards', 'reason')
    op.add_column('test_results', sa.Column('total_points', sa.Integer(), nullable=False))
    op.add_column('test_results', sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('test_results', 'total_score')
    op.drop_column('test_results', 'completed_at')
    op.add_column('tests', sa.Column('source_note_ids', sa.String(), nullable=True))
    op.add_column('tests', sa.Column('source_homework_ids', sa.String(), nullable=True))
    op.add_column('tests', sa.Column('generation_mode', sa.String(length=50), nullable=False))
    op.alter_column('tests', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('topics', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('topics', sa.Column('curriculum_context', sa.Text(), nullable=True))
    op.drop_column('topics', 'confidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.drop_column('topics', 'curriculum_context')
    op.drop_column('topics', 'description')
    op.alter_column('tests', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('tests', 'generation_mode')
    op.drop_column('tests', 'source_homework_ids')
    op.drop_column('tests', 'source_note_ids')
    op.add_column('test_results', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('test_results', sa.Column('total_score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('test_results', 'submitted_at')
    op.drop_column('test_results', 'total_points')
    op.add_column('rewards', sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('rewards', 'description')
    op.drop_column('rewards', 'source_id')
    op.drop_column('rewards', 'source_type')
    op.add_column('questions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('questions', 'correct_answer',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)
    op.alter_column('questions', 'options',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('questions', 'points')
    op.drop_column('questions', 'question_order')
    op.add_column('homework', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('homework', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('homework', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('homework', sa.Column('parent_reviewed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('homework', 'reviewed_at')
    op.drop_column('homework', 'uploaded_at')
    op.drop_column('homework', 'is_reviewed')
    op.drop_column('homework', 'corrected_text')
    op.add_column('gifts', sa.Column('probability', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('gifts', 'updated_at')
    op.drop_column('gifts', 'is_active')
    op.drop_column('gifts', 'points_cost')
    op.add_column('class_notes', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.alter_column('class_notes', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('class_notes', 'uploaded_at')
    # ### end Alembic commands ###
